name: Main

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v2
        with:
          node-version: 19

      - name: Build
        run: pnpm -r build

      - name: Lint
        run: pnpm -r lint

      - name: Test
        run: pnpm -r test

      - name: Setup Postgres
        uses: ikalnytskyi/action-setup-postgres@v3

      - name: Integration test
        run: pnpm -r test:integration
