name: Main

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v4
        with:
          # Remove until https://github.com/sinonjs/sinon/issues/2590 is resolved
          node-version: 20.11.1

      - name: Build
        run: pnpm -r build --sourcemap

      - name: Lint
        run: pnpm -r lint

      - name: Test
        run: |
          pnpm test:all
          rm -rf coverage/tmp

      - name: Setup Postgres
        uses: ikalnytskyi/action-setup-postgres@v3

      - name: Integration test
        run: pnpm -r test:integration

      - uses: codecov/codecov-action@v3
